---

- name: Set Ceilometer Handlers
  set_fact:
    ceilometer_handlers: ['Restart Ceilometer','Restart Ceilometer Alarm']
  when: version in ['kilo', 'liberty']

- name: Set Ceilometer Handlers
  set_fact:
    ceilometer_handlers: ['Restart Ceilometer']
  when: version not in ['kilo', 'liberty']

- name: Install Common Openstack Packages
  package:
    name: '{{ item }}'
    state: latest
  with_items: "{{ openstack_packages }}"

- name: Install Ceilometer Packages
  package: 
    name: '{{ item }}'
    state: latest
  with_items: "{{ ceilometer_packages }}"

- name: Configure Ceilometer
  template:
    src: "ceilometer.conf.{{ version }}"
    dest: "/etc/ceilometer/ceilometer.conf"
    backup: yes
  notify: "{{ ceilometer_handlers }}"

- name: Create Ceilometer User
  keystone_user:
    state: present
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
    user: ceilometer
    tenant: services
    password: "{{ ceilometer.password }}"

- name: Create Ceilometer ResellerAdmin Role
  run_once: yes
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
#   tenant: admin
    role: ResellerAdmin


- name: Grant Ceilometer Admin Role
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
    tenant: services
    user: ceilometer
    role: admin

- name: Grant Ceilometer ResellerAdmin Role
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone.admin_token }}"
    tenant: services
    user: ceilometer
    role: ResellerAdmin

- name: Create Ceilometer Service And Endpoint
  keystone_service: 
    name: ceilometer
    type: metering
    description: "Ceilometer Telemetry Service"
    publicurl: "{{ ceilometer_public_url }}"
    internalurl: "{{ ceilometer_internal_url }}"
    adminurl: "{{ ceilometer_admin_url }}"
    endpoint: "{{ keystone_internal_url }}"
    login_user: admin
    login_password: "{{ keystone.admin_password }}"
    tenant_name: admin
    region: "{{ common.region }}"

- name: Enable Ceilometer Services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ ceilometer_services }}"

- name: Enable Ceilometer Alarm Services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ ceilometer_alarm_services }}"
  when: version in ['kilo','liberty']
