---

- name: Install Neutron Dhcp Packages
  package: 
    name: '{{ item }}'
    state: latest
  with_items: "{{ neutron_packages }}"

- name: Configure Neutron Dhcp
  template:
    src: "dhcp_agent.ini.{{version}}"
    dest: "/etc/neutron/dhcp_agent.ini"
    backup: yes
  notify:
   - Restart Neutron Dhcp

- name: Configure Neutron Dhcp DnsMasq MTU
  copy:
    src: "dnsmasq-neutron.conf"
    dest: "/etc/neutron/dnsmasq-neutron.conf"
    owner: root
    group: neutron
    mode: 0640
  notify:
   - Restart Neutron Dhcp

- name: Enable Neutron Dhcp Service
  service:
    name: "{{ neutron_dhcp_service }}"
    enabled: yes
    state: started
